# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"
  - "3.5"
  # - "3.6"  # TODO: make it work: https://github.com/tensorlayer/tensorlayer/issues/291
install:
  - pip install tensorflow
  - pip install .
script:
  # units test
  # https://docs.pytest.org/en/latest/
  # TODO: make it work
  # - pytest

  # smoke tests
  - python tests/test_mnist_simple.py
